### ISSUE TITLE
Authenticator unable to read qr code

### ISSUE THREAD

**Issue by dilbert2019** [Authenticator-Extension/Authenticator#281] opened 2019-02-08 14:53 UTC
There is a website that uses the authenticator extension in chrome to read the qr code and so forth.

A workstation crashed and we reinstalled everything but the authenticator extension in chrome is not reading the qr code, the error we get is: <Web Address>> unrecognized qr code

Besides installing the authenticator extension is there anything else in chrome that needs to be adjusted to allow this to work properly?

There is one other machine that has this working and able to capture the qr code of the website with an issue.

**Comment by mymindstorm** [comment] 2019-02-09 14:20
Use manual entry. Duplicate of #174

**Closed as completed by mymindstorm** 2019-02-09 14:20 UTC
Labels: duplicate
