### ISSUE TITLE
All authentication data is trashed after entering wrong password several times

### ISSUE THREAD

**Issue by patrakov** [Authenticator-Extension/Authenticator#397] opened 2019-10-21 17:34 UTC
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

Sure, I don't ask. I have a backup for all codes except one, and that one can be easily reset.

**Describe the bug:**

I have added several QR codes, then clicked "Lock", then unlocked it with the wrong password. Expected all codes to show as "Encrypted". Some of them did show as "Encrypted", but not all. Locked again, then again deliberately entered a wrong password. This time, all of them showed up as "Encypted".

Locked again, then entered the correct password. Result: still all "Encrypted". I expected them to unlock.

**Platform:** Arch Linux
 - Browser: Chromium
 - Browser Version: 77.0.3865.120

**Comment by patrakov** [comment] 2019-10-21 17:37
Not sure if it matters, but I have set Authenticator to sync data via Google.

**Comment by mymindstorm** [comment] 2019-10-21 21:46
Are you starting a scan, locking, and then adding the code? 

Did you edit any data or change the position of any entries while some of them were showing as "encrypted"?

Also, please follow [these steps](https://authenticator.cc/docs/en/debug-info) while reproducing the issue.

**Comment by patrakov** [comment] 2019-10-21 22:15
I was not adding any codes after the first entry of the wrong password. I might have tried to rearrange the entries, but did not do any other editing. In other words: need to try again reproducing.

**Comment by mymindstorm** [comment] 2020-02-09 20:02
This should be fixed as of 6.0.1. Can you reproduce with that version?

**Comment by manch-tech** [comment] 2020-03-04 00:27
I have this error in my authenticator.

**Comment by mymindstorm** [comment] 2020-03-04 00:50
@manch-tech I need more info. Please post version, browser, logs, and any steps you took before the issue appeared.

**Comment by manch-tech** [comment] 2020-03-04 01:52
Exactly the same steps as the friend above.  I've been using this extension for 7 years and I've never had a problem, but today it happened. When I enter the password everything appears encrypted. When requesting a password to decrypt, I enter it again and nothing happens. Chrome, last version. Also used in yandex and firefox, but the problem is in chrome.

**Comment by canurit** [comment] 2020-04-22 20:54
same here

**Comment by Meserias** [comment] 2020-09-04 08:44
I know my password for Authenticator-Extension however when I enter it it show Encrypted on all entries.
Please provide solution (Firefox -   80.0.1 x64)

**Closed as completed** 2020-09-04 16:56 UTC
Labels: bug
