### ISSUE TITLE
HOTP code displayed as invalid

### ISSUE THREAD

**Issue by nt1m** [Authenticator-Extension/Authenticator#76] opened 2018-03-11 23:30 UTC
One of the websites I login to requires a Yubikey that uses the OATH-HOTP protocol. Unfortunately, pasting the Yubikey secret key into Authenticator doesn't work.

**Comment by mymindstorm** [comment] 2018-03-11 23:40
Actually I think we already support this, add a secret using manual entry and set the dropdown to "Counter Based"

**Comment by nt1m** [comment] 2018-03-12 09:40
@mymindstorm Doesn't work on my side. It just keeps saying "Invalid" when I try to add my secret key.

**Comment by mymindstorm** [comment] 2018-03-12 16:00
Can you give an example secret so we can reproduce?

**Comment by nt1m** [comment] 2018-03-12 17:28
@mymindstorm 
2c52e8fcfac34091da63ef7b118f1cc50b925a42

**Comment by mymindstorm** [comment] 2018-03-12 18:01
Can reproduce.

**Comment by Sneezry** [comment] 2018-03-12 18:04
It seems we need add a new type for HOTP in HEX format

**Comment by Sneezry** [comment] 2018-03-12 18:47
Fixed in the latest code

**Closed by Sneezry** 2018-03-12 18:47 UTC
Labels: bug

**Comment by nt1m** [comment] 2018-03-12 20:26
Thanks @Sneezry! Has an update been deployed on AMO yet ?

**Comment by mymindstorm** [comment] 2018-03-12 20:28
I'll notify you when I deploy to AMO, we have a few more things to fix before the next update.

**Comment by mymindstorm** [comment] 2018-03-17 03:08
I've uploaded latest version to AMO, update your extension using [these steps](https://github.com/Authenticator-Extension/Authenticator/issues/64#issuecomment-370291688) @nt1m

**Comment by nt1m** [comment] 2018-03-17 14:07
@mymindstorm The latest version doesn't seem available on AMO yet: https://addons.mozilla.org/en-US/firefox/addon/auth-helper/versions/

But I downloaded the version from Github releases, and it works great! 

Thanks for fixing this so quickly :)

**Comment by mymindstorm** [comment] 2018-03-17 14:20
Sorry about that, I had to disable 4.0.7 due to it an issue with Dropbox
OAuth getting broken. It's probably going to automatically downgrade itself
when it checks for updates.

On Mar 17, 2018 9:07 AM, "Tim Nguyen" <notifications@github.com> wrote:

@mymindstorm <https://github.com/mymindstorm> The latest version doesn't
seem available on AMO yet:
https://addons.mozilla.org/en-US/firefox/addon/auth-helper/versions/

But I downloaded the version from Github releases, and it works great!

Thanks for fixing this so quickly :)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Authenticator-Extension/Authenticator/issues/76#issuecomment-373922672>,
or mute the thread
