### ISSUE TITLE
Autofill can't be used in Firefox

### ISSUE THREAD

**Issue by quick3210** [Authenticator-Extension/Authenticator#855] opened 2022-02-12 05:36 UTC
### Describe the issue

I open the autofill, but it still can't autofill into a textbox. What's wrong?

### Browser

Firefox

### Browser Version

97.0

### Extension Version

6.3.4

**Comment by kolAflash** [comment] 2022-09-04 14:46
Probably a duplicate of #878: _Prompt for <all_sites> permission in Firefox when enabling autofill_

**Closed as completed** 2023-04-20 03:48 UTC
Labels: bug, duplicate
