### ISSUE TITLE
Error recognizing QR code

### ISSUE THREAD

**Issue by stephanmit** [Authenticator-Extension/Authenticator#277] opened 2019-02-06 08:14 UTC
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Describe the bug:** <After selecting the QR code on the screen, I get the message that the QR code cannot be recognized> 

**Platform:** <Windows 7 and Windows 10 Enterprise>
 - Browser: [Chrome]
 - Browser Version: 72.0.3626.81

**Comment by mymindstorm** [comment] 2019-02-07 01:13
Duplicate of #174, just enter code manually.

**Closed as completed by mymindstorm** 2019-02-07 01:13 UTC
Labels: duplicate
