### ISSUE TITLE
Amazon TOTP no longer functioning

### ISSUE THREAD

**Issue by IMSTechDept** [Authenticator-Extension/Authenticator#95] opened 2018-03-19 16:27 UTC
Amazon TOTP codes only display "Invalid" in version 5.0.7

Is there a workaround for this?

<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Comment by Sneezry** [comment] 2018-03-19 17:57
Is your secret encrypted? Is Amazon account the only one display Invalid or all your code changes to Invalid?

**Comment by IMSTechDept** [comment] 2018-03-19 18:08
Only Amazon shows Invalid. Nothing is encrypted, and I have reproduced this issue on multiple computers. Whether using a manual method or the automatic QR scan, the code shows "Invalid" for Amazon accounts, and ONLY amazon accounts.
![authissue](https://user-images.githubusercontent.com/29929213/37613604-6f8b851c-2b76-11e8-8bba-8f3768b12487.PNG)

**Comment by Sneezry** [comment] 2018-03-19 18:13
So even you add a new Amazon account, the code display Invalid, right? Is Amazon always display Invalid or only for some code?

**Comment by Sneezry** [comment] 2018-03-19 18:16
I can repro with `QLGNXJ2KLSOACXOEKJ47X6VA6ZPGT5HE2GBO5NPXTLD7FJAKD4JQ`

**Comment by Sneezry** [comment] 2018-03-19 18:34
The problem is caused by missing pad. Base32 should contains pad (=) if the original string is not in byte length of n*40.

The secret above is `82ccdba74a5c9c015dc45279fbfaa0f65e69f4e4d182eeb5f79ac7f2a40a1f130` after decode to HEX, which length is 65. Odd length hex makes the exception.

The correct Base32 string of the secret should be `QLGNXJ2KLSOACXOEKJ47X6VA6ZPGT5HE2GBO5NPXTLD7FJAKD4JQ=`.

I think this should be Amazon's bug, they did not follow [rfc4648](https://tools.ietf.org/html/rfc4648).

However, we will do some extra work in v5.0.8 to make the extension compatible with Amazon.

**Comment by Sneezry** [comment] 2018-03-21 05:20
fixed in the recent code.

**Closed as completed by Sneezry** 2018-03-21 05:20 UTC
Labels: bug
