### ISSUE TITLE
Don't working export to file.

### ISSUE THREAD

**Issue by mrResident** [Authenticator-Extension/Authenticator#99] opened 2018-03-23 09:15 UTC
I want export data to file, but this function don't work! How export data to file? How wokring function - sunc data to Dropbox?

**Comment by Sneezry** [comment] 2018-03-23 09:28
I believe this issue is caused by new version of Chrome, because it works in old version Chrome.

Right click Download button, and select save as, then you can get the backup file.

**Comment by mrResident** [comment] 2018-03-23 09:48
> Right click Download button, and select save as, then you can get the backup file.

Thanks, this is working!

And also, when I set the master password in the security settings, then always requested a password and there is no way to do anything (change the password, export / import data, add new data). The following message is displayed

"You can not add a new account or display the data until all the accounts have been logged in. Please enter the correct password before continuing"

In which accounts do I have to log in?

**Comment by jb90126** [comment] 2018-03-23 09:50
Does backup with all authenticators have .json extension ?

**Comment by mrResident** [comment] 2018-03-23 10:06
> Does backup with all authenticators have .json extension ?

Yes, when I right clicked on Download button and selected save as, appearing file authenticator.json with all my keys.

**Comment by Sneezry** [comment] 2018-03-23 16:30
@mrResident Does the message show even when you enter correct password? Is there any entry display as `Encrypted`?

**Comment by mrResident** [comment] 2018-03-23 21:20
@Sneezry 

> Does the message show even when you enter correct password?

Yes, this message appears every time I enter the correct password. As a result, I can not access the settings, because the window with this message always appears. Also I can not add new data. In general, after I set the master password, I can not really do anything.

> Is there any entry display as Encrypted?

You mean the "encrypted" field: in a json file that I export from the program? I can not upload data to a file in json format because of the message I wrote about already.

"You can not add a new account or display the data until all the accounts have been logged in. Please enter the correct password before continuing"

**Comment by germdove** [comment] 2018-03-24 23:06
I was getting the same thing. I had to delete the accounts marked as encrypted and take my master password off before reimporting to get my accounts back.

**Comment by Sneezry** [comment] 2018-03-26 02:33
Fixed in the recent code.

**Closed as completed by Sneezry** 2018-03-26 02:33 UTC
Labels: bug, chrome
