### ISSUE TITLE
 Cannot decrypt some accounts after firefox 79 update

### ISSUE THREAD

**Issue by erotavlasme** [Authenticator-Extension/Authenticator#517] opened 2020-07-30 07:01 UTC
Hi,
after the upgrade to latest firefox 79, when I open the extension and I unlock it with password, not all my accounts are visible. Some of them remain encrypted. It is the same problem of [this](https://github.com/Authenticator-Extension/Authenticator/issues/428). I'm using the latest firefox 79, with latest authenticator 6.2.1 on GNU/linxu 64 bit.

**Comment by mymindstorm** [comment] 2020-07-30 17:22
Please open your console, unlock authenticator, and then copy and paste all logs here.

**Comment by erotavlasme** [comment] 2020-07-31 06:27
I'm sorry, but I cannot help you. Since I had to use some of my accounts, I deleted and restored the accounts on authenticator from a file backup.

**Comment by mymindstorm** [comment] 2020-07-31 19:14
I can only guess what caused it if that is the case. https://blog.mozilla.org/addons/2020/07/09/changes-to-storage-sync-in-firefox-79/ might be related. What distro are you using?

**Comment by erotavlasme** [comment] 2020-08-01 07:29
It could be the source of problem. I'm using ubuntu mate 16.04 64 bit.

**Comment by mymindstorm** [comment] 2020-08-03 16:29
I ran into this, it's definitely related to the Firefox 79 update.

**Comment by erotavlasme** [comment] 2020-08-04 05:51
Any way to fix it? So other users will not have the same problem.

**Comment by mymindstorm** [comment] 2020-08-04 19:40
It's up to Mozilla to fix Firefox, there isn't much I can do on this end.

**Comment by erotavlasme** [comment] 2020-08-05 05:30
Did you modify your code according to the requirements of firefox 79 that you reported?

**Comment by Sneezry** [comment] 2020-08-05 05:47
@mymindstorm correct me if I have any mistake. As far as I know, new sync storage in Firefox 79 only changes data quota:

> If you are the developer of an extension that syncs extension storage, you should be aware that the new implementation now enforces client-side quota limits.

I have checked the new quota: max to 512 entries, max to 8KB every entry, max to 100KB in total. I think that quota should be fine, and that should be the root cause. And I don't think we need modify any code to migrate to the new sync storage.

> If your extension previously stored data above quota limits, all that data will be migrated and available to your extension, and will be synced. However, attempting to add new data will fail.

Even the quota is hit, the data is still safe to read. Only new data cannot be saved. So unable to decrypt data/data breaks is another issue.

**Comment by mymindstorm** [comment] 2020-08-05 18:09
> Did you modify your code according to the requirements of firefox 79 that you reported?

There are no changes required from our side outside of possibly adding a warning when getting close to the quota. This limitation has already been on Chrome for some time.

> As far as I know, new sync storage in Firefox 79 only changes data quota

It also migrates extension storage to another format. I don't know how, but I was able to reproduce this yesterday. There were a lot of unknown error messages from the storage manager, and my sync data was all messed up. As you said, the quota shouldn't mess reading data up even if it is hit.

> The storage.sync area has been ported to a new Rust-based implementation, allowing extension storage to share the same infrastructure and backend used by Firefox Sync.

> Extension data that had been stored locally in existing profiles will automatically migrate the first time an installed extension tries to access storage.sync data in Firefox 79. After the migration, the data will be stored locally in a new storage-sync2.sqlite file in the profile directory.

Mozilla is already aware of this issue. I am closing this in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1635351 and https://bugzilla.mozilla.org/show_bug.cgi?id=1624586

**Closed as completed by mymindstorm** 2020-08-05 18:09 UTC
Labels: bug

**Comment by erotavlasme** [comment] 2020-08-05 20:30
The two bugs reported are duplicate of each other. Moreover, they are not related to firefox 79, but firefox 75. Maybe, the problem was already present since firefox 72 as I reported in my first message.

**Comment by mymindstorm** [comment] 2020-08-05 20:38
> The two bugs reported are duplicate of each other.

I included the first link for context, the second is still open.

> Moreover, they are not related to firefox 79, but firefox 75. 

Yes, that's why I thought it was related, I should have been more clear. Those bugts line up pretty well with all three occurrences of this. The 79 changes could have indirectly caused this to happen again.

**Comment by erotavlasme** [comment] 2020-08-06 14:27
Ok thank. I think that I found another related problem. If I change some preferences (theme, autofill and lock) they are restored to default setting after a while.

**Comment by mymindstorm** [comment] 2020-08-06 16:24
Are you clearing browsing data often? Extension settings get cleared when you clear browsing data.

**Comment by erotavlasme** [comment] 2020-08-06 19:46
Periodically, I delete cookies, history and data. Should not extension settings be independent from browser data? I have many other extensions that have not this problem.

**Comment by mymindstorm** [comment] 2020-08-06 20:05
https://bugzilla.mozilla.org/show_bug.cgi?id=1313401

**Comment by erotavlasme** [comment] 2020-08-07 06:25
Ok, I know about this bug. How can other extensions store and maintain their settings?

**Comment by mymindstorm** [comment] 2020-08-08 14:55
We store user account data using a WebExtension storage API and user settings using localstorage. WebExtension storage does not get cleared while localstorage does. From the bug, it looks like this will be fixed with the storage changes introduced in FF79.
