### ISSUE TITLE
Trello's QR code unrecognized

### ISSUE THREAD

**Issue by falko** [Authenticator-Extension/Authenticator#393] opened 2019-10-17 11:54 UTC
**Describe the bug:**
Scanning Trello's QR code fails with the message "unrecognized QR code".

**Platform:**
 - Browser: Firefox Quantum on Ubuntu 18.04.3 LTS
 - Browser Version: 69.0.2 (64-bit)

**Comment by falko** [comment] 2019-10-17 11:55
It could be related to #386 but I tried to at least scoll in a way that the codes don't overlap

**Comment by mymindstorm** [comment] 2019-10-17 14:04
@falko It's not related to #386 ([my comment](https://github.com/Authenticator-Extension/Authenticator/issues/386#issuecomment-528127100)), that overlay is not captured when scanning. This is probably just a duplicate of #174. Overlapping the code with the picture has no adverse effects. Make sure you cover the code completely. Leave some white space around the edges. If that doesn't help, then follow [these directions](https://authenticator.cc/docs/en/debug-info#firefox), scan a code, and paste any error messages into the issue. If none of this works, then just use the manual entry method (edit, scroll to bottom, click plus).

**Comment by Sneezry** [comment] 2020-05-19 02:38
We have added jsQR lib for a secondary solution if it fails with the first try. Let's see if this issue migrates

**Comment by Sneezry** [comment] 2020-05-19 02:41
Let's track all QR related issues https://github.com/Authenticator-Extension/Authenticator/issues/174, and close this thread.

**Closed as completed by Sneezry** 2020-05-19 02:41 UTC
Labels: bug, QR
