### ISSUE TITLE
Crash with Vivaldi 4.3

### ISSUE THREAD

**Issue by skogtun** [Authenticator-Extension/Authenticator#759] opened 2021-10-07 11:30 UTC
### Describe the issue

The extension crashes when using the latest Vivaldi stable for Linux. 

### Browser

Other

### Browser Version

4.3.2439.39 (Stable channel) stable (64-biters)

### Extension Version

b56b5c434ef763fa8d9ee8c48fd50c20887f5974

**Comment by Rewerson** [comment] 2021-10-08 05:44
I confirm the same behaviour on Windows build of Vivaldi.

**Comment by Sneezry** [comment] 2021-10-08 07:08
Hi @skogtun , thanks for the feedback. You may need ask Vivaldi to help to fix the crash issue for the extension here: https://forum.vivaldi.net/category/2/support-troubleshooting

**Comment by Rewerson** [comment] 2021-10-08 07:15
> Hi @skogtun , thanks for the feedback. You may need ask Vivaldi to help to fix the crash issue for the extension here: https://forum.vivaldi.net/category/2/support-troubleshooting

It's already: https://forum.vivaldi.net/topic/67228/extension-authenticator-crashes
Could we ask you nicely whether something could be done about it? :)
I also consider it's Vivaldi problem, but maybe you can give some useful info from your side to provide it to them?

**Comment by Sneezry** [comment] 2021-10-08 08:01
Hi @Rewerson thanks for the feedback URL in Vivaldi. I have tested Vivaldi on my side, and I can reproduce the issue. However, I cannot get any additional information about the issue. I have no chance to debug the extension, its window just flash to disappear and Vivaldi told me the extension has been crashed without any details :(

**Comment by Sneezry** [comment] 2021-10-25 09:55
![image](https://user-images.githubusercontent.com/1621293/138674885-477cc481-4167-4d47-b3f1-c3f30f7a56bb.png)

Vivaldi has fixed this issue, and the fix will be available in the next release.

**Comment by skogtun** [comment] 2021-10-25 10:06
Zhe Li [25/10/2021 11.55]:

> Vivaldi has fixed this issue, and the fix will be available in the next 
> release.

Good, waiting for next snapshot then.
-- 
Hilsen Harald

**Comment by Sneezry** [comment] 2021-11-08 05:06
I'm closing this issue because Vivaldi has marked the bug as resolved.

**Closed as completed by Sneezry** 2021-11-08 05:06 UTC
Labels: bug

**Comment by skogtun** [comment] 2021-11-08 08:59
Zhe Li [08/11/2021 06.06]:

> I'm closing this issue because Vivaldi has marked the bug as resolved.

It is indeed fixed in the latest Vivaldi.
-- 
Hilsen Harald
