### ISSUE TITLE
Sync is not working

### ISSUE THREAD

**Issue by just-automatic** [Authenticator-Extension/Authenticator#681] opened 2021-06-05 04:57 UTC
**Describe the bug:** <Describe the issue with Authenticator> 

**This is a bug on version 6.3.2, since I reinstalled 6.3.0 on the Microsoft store and loaded the unpacked extension in Google Chrome, it worked perfectly.**

The sync function is completely broken, when you click "manual backup", the console gives me the following error:
```
Uncaught (in promise) TypeError: Cannot read property 'getEncryptionStatus' of undefined
    at Function.<anonymous> (popup.js:9)
    at popup.js:9
    at Object.next (popup.js:9)
    at popup.js:9
    at new Promise (<anonymous>)
    at o (popup.js:9)
    at popup.js:9
    at r (popup.js:9)
```
Happens every time, no matter you choose encrypted or not.

**Platform:** <This is required>
 - Browser: Google Chrome
 - Browser Version: Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by mymindstorm** [comment] 2021-06-05 20:33
Closing as duplicate of #676

**Closed as completed by mymindstorm** 2021-06-05 20:33 UTC
Labels: bug
