### ISSUE TITLE
Authenticator will not overwrite old code on page with new code after old has expired due to capcha's.

### ISSUE THREAD

**Issue by famewolf** [Authenticator-Extension/Authenticator#580] opened 2021-01-14 22:07 UTC
<Do not use this to ask about lost codes or accounts>
<More info here: https://authenticator.cc/docs/en/lost-codes>

If otp code expires and a new code is generated overwrite the OLD code on page.

Why is this an issue?
M1 finance and I'm sure other pages occasionally throw in a capcha after you've entered the code.  If they require you to do multiple ones when you get BACK to the screen to click submit the otp code is sometimes invalid and submitting it will just start things over.  Currently Clicking on authenticator and selecting the site with copy the new code to clipboard but does not autofill to the page because that field already has content (the old code).

If I didn't explain this clearly enough please let me know.

**Platform:** Linux
 - Browser: Brave
 - Browser Version: Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

**Comment by Sneezry** [comment] 2021-01-15 02:49
Here's the root cause:

https://github.com/Authenticator-Extension/Authenticator/blob/63ea3e587c1c740fd701a4e02d90ed4168952688/src/content.ts#L228-L231

We only auto fill the code if the input box is blank. I think we can also check if its value is some digits, and if yes, we can overwrite its value.

**Comment by famewolf** [comment] 2021-01-15 16:27
Wow ya'll are fast!  Thank you for your hard work!

**Comment by Sneezry** [comment] 2021-03-23 06:08
This issue should be fixed in 6.3.0

**Closed as completed by Sneezry** 2021-03-23 06:08 UTC
Labels: bug
