### ISSUE TITLE
Insert code into current text field

### ISSUE THREAD

**Issue by Frohmen** [Authenticator-Extension/Authenticator#142] opened 2018-06-07 11:36 UTC
It would be great if Authenticator when clicking on a code instead of copying it would insert it into the current text field. This would ease up the use of having to paste the code into the required text field.

Thanks in advance!

**Comment by mymindstorm** [comment] 2018-06-07 16:14
Duplicate of #73

**Closed as completed by mymindstorm** 2018-06-07 16:14 UTC
