### ISSUE TITLE
All codes are invalid

### ISSUE THREAD

**Issue by coty-crg** [Authenticator-Extension/Authenticator#89] opened 2018-03-17 04:23 UTC
Recently had to reinstall windows. I kept my appdata folders and stuff, though. Reinstalled chrome and chrome auto installed the plugin, but now all of my codes show as invalid. I tried following the guide to reimport old codes, but they still show as invalid after successfully guessing my password. 

https://i.imgur.com/nf1TNIq.png

**Comment by mymindstorm** [comment] 2018-03-17 04:35
What version are you on? We recently released 5.0.7 which has a fix for some secrets displaying as invalid.

**Comment by coty-crg** [comment] 2018-03-17 04:44
https://i.imgur.com/WAhKmck.png

Seems like its the latest. I have the backup file still, so its not huge I suppose. Will just wait for a fix (I have all the codes on my phone too, was just using this extension as the backup)

**Comment by mymindstorm** [comment] 2018-03-17 04:46
By guide to reimport old codes do you mean [this](https://github.com/Authenticator-Extension/Authenticator/issues/63#issuecomment-370219224)?

Can you follow [these steps](https://github.com/Authenticator-Extension/Authenticator/wiki/Getting-Debugging-Information#chrome) and paste any messages here?

**Comment by coty-crg** [comment] 2018-03-17 04:49
Sorry my dude, no errors in the console. 

https://i.imgur.com/6fOyo4u.png

Crazy coincidence though, I didn't realize you just pushed out a release. Sorry for the instant error report, I know how it feels.

**Comment by Sneezry** [comment] 2018-03-17 05:49
You should be able to download backup file, click export/import, then download backup file. Open it with notepad or other editor, search `secret`, what is the length of the string after `secret`?

For example as below, the string is `abcd2345`, its length is 8:

<img width="352" alt="screen shot 2018-03-17 at 13 48 34" src="https://user-images.githubusercontent.com/1621293/37552140-fe29fa9e-29e9-11e8-8353-0178c52a7455.png">

**Comment by mymindstorm** [comment] 2018-03-17 05:50
@coty-crg not going to lie, you scared the hell out of me with that title.

**Comment by mymindstorm** [comment] 2018-03-19 06:42
@Sneezry I was able to make this happen on a newer version after getting my encryption password wrong a few times. No data got messed up, just didn't get replaced with encrypted instead showed invalid

**Comment by Sneezry** [comment] 2018-03-19 07:45
The problem is that we do not know if the password is correct - we try to decrypt the secret with the provided password, and we can even get result with incorrect password sometimes (most of time we get an exception when user provides an incorrect password).

If the secret before encrypt in binary is 

```
0A 1F 36 2C ...
```

it may change with incorrect password

```
2D 5F
```

Then we encrypt it with the incorrect password and save it to `chrome.storage.sync` again when we try to migrate data with import method. Such as ensure index unique.

A workaround is we can verify if a decrypted secret is in Base32 or HEX format, and show `Encrypted` if it is not.

**Comment by Sneezry** [comment] 2018-03-19 08:00
Here's an example:

secret is `abc`, password is `12345678`, and encrypted secret is

```
U2FsdGVkX1+3bUhftRIje58yj9DkQ64RjBFYjUmEg5I=
```

It is easy to verify with 

```
CryptoJS.AES.decrypt('U2FsdGVkX1+3bUhftRIje58yj9DkQ64RjBFYjUmEg5I=', '12345678').toString(CryptoJS.enc.Utf8) === 'abc'
```

However, we can get another secret with an incorrect `12345677` without exception:

```
CryptoJS.AES.decrypt('U2FsdGVkX1+3bUhftRIje58yj9DkQ64RjBFYjUmEg5I=', '12345677').toString(CryptoJS.enc.Utf8)
```

And now, the secret has changed to `Mr`.

**Comment by coty-crg** [comment] 2018-03-21 02:49
Sorry, missed this for a few days. Not at my PC right now, but I have a strong feeling you're correct. I had to guess my password a few times to get it to display anything. Must be that it was wrong

**Comment by Sneezry** [comment] 2018-03-21 06:01
fixed in the recent code

**Closed as completed by Sneezry** 2018-03-21 06:01 UTC
Labels: bug
