### ISSUE TITLE
Insert code into current text box

### ISSUE THREAD

**Issue by Frohmen** [Authenticator-Extension/Authenticator#123] opened 2018-04-18 09:16 UTC
First I would like to thank you for a great extension.
This is actual not an issue but a feature request and I didn't find anywhere else to post it.

It would be great if there where an Insert button next to each code, which would insert the code into the current text box.

**Comment by mymindstorm** [comment] 2018-04-18 17:55
duplicate of #73, that is the closest we would get to that sort of feature if something like that was implemented

**Closed as completed by mymindstorm** 2018-04-18 17:55 UTC
Labels: duplicate

**Comment by mymindstorm** [comment] 2018-04-18 17:57
Also, thanks for your work on Crowdin! It will be shipped with 5.0.10
