### ISSUE TITLE
Secret's string converted to URL encoding after import from backup

### ISSUE THREAD

**Issue by isumairu** [Authenticator-Extension/Authenticator#502] opened 2020-07-10 08:59 UTC
I exported my secrets (using 'Download Backup File') before i do clean install of my browser, then imported the backup file.
I noticed that the name and account address were converted to URL encoding  ('space' to '%20' etc)
![tempsnip](https://user-images.githubusercontent.com/16854686/87136609-f00dbf00-c2c5-11ea-9a24-451fb0a13b54.jpg)
Like that "Microsoft%20main%203" it was "Microsoft main 3" before export-import.

How to recover my secrets to normal?

 - Browser: Firefox
 - Browser Version: 78.0.2 x64

**Comment by mymindstorm** [comment] 2020-07-16 00:49
Duplicate of #416

**Closed as completed by mymindstorm** 2020-07-16 00:49 UTC
Labels: bug
