### ISSUE TITLE
Token with and 7 digits codes

### ISSUE THREAD

**Issue by emericv** [Authenticator-Extension/Authenticator#300] opened 2019-03-10 22:33 UTC
Hello, It's not possible to add a token with and 7 digits codes (used with some services).
Result : the interface display 6 instead of the 7 digits
Thanks in advance :)

 - Browser: Firefox
 - Browser Version: NA

**Comment by emericv** [comment] 2019-03-10 22:36
Similar issue onkeepassxc to illustrate: https://github.com/keepassxreboot/keepassxc/issues/1762

**Comment by mymindstorm** [comment] 2019-03-10 22:58
Duplicate of #287

**Closed as completed** 2019-03-10 22:58 UTC
