### ISSUE TITLE
Add option to increase OTP expiration for visually impaired people

### ISSUE THREAD

**Issue by cipineda** [Authenticator-Extension/Authenticator#1175] opened 2024-04-02 16:15 UTC
### Describe the issue

We use this Authenticator and works great, thanks for creating this.
We do have a request though. Is it possible to add an option  to extend the duration of the OTP?
We have people that are visually impaired or have other type of restriction based on ADAAA.
They are slower to copy/paste, switch screens, etc in order to complete the MFA authentication, and 30 seconds does is not enough for them.
Your help is greatly appreciated.

### Browser

Firefox

### Browser Version

124.0

### Extension Version

6.3.5

**Comment by mymindstorm** [comment] 2024-04-02 16:23
Duplicate of #1176

**Closed as not planned by mymindstorm** 2024-04-02 16:23 UTC
Labels: bug
