### ISSUE TITLE
emulate keystrokes when pasting the code to form inputs

### ISSUE THREAD

**Issue by aleqx** [Authenticator-Extension/Authenticator#284] opened 2019-02-17 16:56 UTC
Currently the extension automatically fills the code on the form input that has focus, but it does so by changing its value. Many websites (surprisingly many!) are checking for keystrokes instead. That is, even with the value filled in by the extension,t hey complain that the field is not filled in.

Could you please also fire all the keyboard related events for that form input (keypress, keydown, keyup) to get around this?

**Comment by mymindstorm** [comment] 2019-02-22 02:35
Duplicate of #253

**Closed as completed by mymindstorm** 2019-02-22 02:35 UTC
Labels: bug, duplicate
