### ISSUE TITLE
can't add new manual entry

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [Authenticator-Extension/Authenticator#408] opened 2019-12-09 16:51 UTC
I can't add new (second) entry to the list. I can open new manual entry dialog box, fill it up, but when i click "ok" - nothing happens. It just stays there.

 - Browser: Chrome
 - Browser Version: Version 78.0.3904.108 (Official Build) (64-bit)

**Comment by mymindstorm** [comment] 2019-12-09 23:37
Please follow [these steps](https://authenticator.cc/docs/en/debug-info).

**Comment by Vasiliy-Bondarenko** [comment] 2019-12-10 07:36
@mymindstorm 
ok. sure.
```
Error handling response: Error: The specific entry has already existed.
    at chrome-extension://bhghoamapcdpbohphigoooaddinpkbai/build/models/storage.js:297:31
```
the code i am trying to enter does not exist in my list right now.

**Comment by mymindstorm** [comment] 2019-12-10 15:18
@Vasiliy-Bondarenko your other entry's secret has the same hash as the one you are trying to add. This is fixed in #395, but that fix is not out yet.

**Comment by Vasiliy-Bondarenko** [comment] 2019-12-11 06:58
it's was not the same. 
as i said "the code i am trying to enter does not exist in my list right now."
may be it WAS there before, but definitely not at the time of adding new entry.

strangely enough today i was able to add new code :) was it an update recently?..

**Comment by Vasiliy-Bondarenko** [comment] 2019-12-11 08:32
also i have just mentioned it was displaying wrong codes. code for one account was displayed on the other account (compared to android app, and i have checked - codes from android app work fine, while from authenticator app was not accepted). 

so i deleted all codes and recreated from scratch - now it's fine. 
i guess my authenticator's "database" was in some kind of broken state. 
may be you have some kind of `array[index+offset]` issue in the code.

**Comment by Sneezry** [comment] 2019-12-11 08:34
Hi @Vasiliy-Bondarenko , can you see the specific entry in backup file?

You can export backup file from **Settings** -> **Export / Import** -> **Donwload Backup File**.

**Comment by Vasiliy-Bondarenko** [comment] 2019-12-11 08:44
as i said after recreating all entries - i don't see any problems. i have tried to move them around, delete random items and create new ones - no issue observed. so it's all fine for now. but it was there before! :))) 
if it was that index-offset issue - you can prevent it by using objects with named entries instead of number indexes. 
i have no idea how to recreate the issue now.
i guess you can just wait until someone hit it again and report :) the problem is people probably will just delete the plugin because it's just "not working" and do not report the issue.
if i hit the problem again - i will definitely make a backup and provide more details.

**Comment by Sneezry** [comment] 2019-12-11 08:51
Hi @Vasiliy-Bondarenko , I understand this issue troubles you much, and I'm really sorry about it.

However, it's hard to find out the reason of the issue if we do not have reproduce steps. Theoretically, we locate entries by their hash keys, but not the order, so the order should not be where the problem lies.

Thanks for your feedback, we will keep eyes on this issue.

**Closed as completed** 2020-02-05 00:49 UTC
Labels: bug
