### ISSUE TITLE
autofill issue on Discourse based forums

### ISSUE THREAD

**Issue by ghost** [Authenticator-Extension/Authenticator#253] opened 2018-12-04 11:27 UTC
<Do not use this to ask about lost codes or accounts>
<More info here: https://github.com/Authenticator-Extension/Authenticator/wiki/Lost-Codes>

**Describe the bug:** <Describe the issue with Authenticator> 
Autofill is pasting the TFA code correctly into the website's field but when pressing the Log In button the website displays

>  Invalid authentication code. Each code can only be used once.

Pasting the code manually however does not incur such issue and works without problem.

This happens on forums based on the Discourse discussion platform, e.g. https://forum.openwrt.org/ 

**Platform:** <This is required>
 - Browser: Firefox _x64 on WIN 10 Pro v1809 b17763.134
 - Browser Version:  63.x and above

**Comment by n8v8R** [comment] 2018-12-04 11:53
Seems that with the browser setting `network.http.referer.spoofSource` set to `true ` the issue is apparent. Reverting to its default `false`  remedies the matter.

**Comment by Sneezry** [comment] 2018-12-05 21:32
It works fine on my side. Can you verify that again?

**Comment by n8v8R** [comment] 2018-12-05 21:55
![auth issue](https://user-images.githubusercontent.com/13611490/49546543-68d1bb80-f8d8-11e8-8d21-10b7bb4966a9.png)

**Comment by mymindstorm** [comment] 2018-12-05 22:36
Confirmed:

![bug-low-quality](https://user-images.githubusercontent.com/27789806/49548584-cbf92900-f8ab-11e8-9c31-c96908ce9fa7.gif)

**Comment by Sneezry** [comment] 2018-12-06 04:12
It seems a Firefox specific issue. I tested it on Chrome, and it works fine.

**Comment by PentagramTr** [comment] 2019-02-21 04:22
Has there been any progress on this issue?

**Comment by aleqx** [comment] 2019-02-22 02:44
This is not just firefox, and not just Discourse. As I explained in https://github.com/Authenticator-Extension/Authenticator/issues/284 (which was just marked duplicate of this) it's because the form is actually testing keyboard presses (look for keypress/keyup/keydown events) whereas the extension just changes the input element's value without triggering any of those events. The form javascript validation hence fails as a result. There are a lot of websites doing this - the reason I guess it's because they want to restrict bots as much as possible.

The fix is fairly straightforward. Just trigger all those events of the input after pasting (or better yet, trigger them in sequence and paste characters one by one) to make sure the form validator is happy.

**Comment by mymindstorm** [comment] 2019-02-22 03:04
@aleqx I'm fully aware. Discourse looks for `keydown`, I'm just about to make a PR with these exact changes. Just have to test it works before pushing.

**Closed as completed** 2019-02-22 22:52 UTC
Labels: bug, firefox

**Comment by aleqx** [comment] 2019-03-04 19:26
I just tried master in order to test the new PR, compiled it for Chrome and installe dit in chrome as an unpacked extension. Now it doesn't fill in form fields at all :( ... am I missing anything?

**Comment by mymindstorm** [comment] 2019-03-06 00:38
@aleqx I just built from dev and tested in chrome and it seems to work. Can you give a few more details or error logs?

**Comment by aleqx** [comment] 2019-03-06 01:26
I would have thought the details I provided are sufficient, but it's odd it works for you. Where exactly did you test it? Do you have a public URL that we can both use?

Steps I made:
- pulled master
- built for chrome
- uninstalled chrome extension that i had from web store (after I exported my entries to file)
- installed unpacked extension that I just built
- imported entries from file
- went to use it on known websites, clicking or double-clikcing on an entry in the extension window used to also copy/paste the TOTP into the web form input. Now it copies to clicpboard, but doesn't paste nor types it into the web form input.

**Comment by Sneezry** [comment] 2019-03-06 02:12
@aleqx autofill is disabled by default, did you check it in popup page settings? I notice you missed this step in your comment above.

**Comment by aleqx** [comment] 2019-03-06 02:25
Ha! I was mislead that it's only for the popup mode, because that option is in the "popup" page (you shoul dprobably fix that).

**Comment by aleqx** [comment] 2019-03-06 02:41
Ok, tested on pro.coinbase.com (withdrawal form, not login form) and it behaves like before: it pastes, but the websites complains ... still detects it wasn't typed.

**Comment by mymindstorm** [comment] 2019-03-07 02:23
@aleqx if you open coinbase in firefox  and check the event listeners on it can you get a screenshot of it? Like the following but on the `<input>` for the otp entry.
![image](https://user-images.githubusercontent.com/27789806/53927790-7fa9ba80-404d-11e9-879e-ed75475aec15.png)

Also are you building `master` or `dev`? We don't use the branch named master.

**Comment by aleqx** [comment] 2019-03-07 11:27
I'll do it later. So far it actually doesn't work on any website I've tried. It seems it still just sets the input value but whatever events the website expects are not fired. I had cloned the latest dev.

**Comment by aleqx** [comment] 2019-03-10 15:45
It doesn't seem to be working on of the websites that previously were failing -- they all still fail. Screenshot and source below, but I don't think it will help you because many keyboard events may be hooked up in `body` (or elsewhere) and the element checked within the handler, it doesn't have to be an event attached to the input field.

You should do your own testing (just create an account on Coinbase and activate 2fa). But like I said, all website that were previously failing are still failing.

Firefox: https://i.gyazo.com/aed507f0e789a000ca3e564612b07466.png

https://assets.coinbase.com/exchange/js/main.865ecf246fd05bd2afb5.js

handler seems to be this

https://i.gyazo.com/0e1d0613817b46fe070689df9bdb3a22.png

**Comment by ghost** [comment] 2019-03-16 21:18
if it is not working/fixed then perhaps the status of this issue should be reverted to open?

**Comment by mymindstorm** [comment] 2019-03-22 01:20
Not all sites look for the same things in the same places. It's impossible for us to do everything the way each website expects us to. Right now, it's sending keyboard events after inputting, which should cover most of this issue. Usually, if it fills the OTP field and submit doesn't work all you need to do is backspace one number and put it in manually.

**Comment by aleqx** [comment] 2019-03-22 01:24
Not sure if you read read my message carefully - it doesn't work on _any_ website that requires keyboard presses, at least not on the 15+ different ones that I tried.

**Comment by mymindstorm** [comment] 2019-03-22 01:25
@aleqx I'll test it again on Discorse, are there any other than coinbase that you can give me?

**Comment by ghost** [comment] 2019-04-04 21:51
Has the code been merged yet into the release branch? With the extension's version 5.3.1 it does not work on the Discourse discussion platform.

Thus wondering why this bug's status remains as closed?

**Comment by mymindstorm** [comment] 2019-04-05 00:18
Tested it in Firefox, and OpenWRT's fourm worked fine. I'll test it again with a release build.

**Comment by ghost** [comment] 2019-04-05 08:21
As far I can discern the code was only merged into the dev branch but not the release branch.

Tested with 5.3.1 release on OpenWRT with FF 68.0a1 (2019-04-04) and 66.0.2 (64-bit) on W10 v1809 b17763.379 x_64 and neither is working.

**Comment by mymindstorm** [comment] 2019-04-05 19:51
> As far I can discern the code was only merged into the dev branch but not the release branch.

It looks like it's there to me? There are no differences between dev and release right now. See https://github.com/Authenticator-Extension/Authenticator/compare/dev...v5.3.1 and the follwing

https://github.com/Authenticator-Extension/Authenticator/blob/ec4772793b5d234ef1181d6098efec442333bb06/src/content.ts#L227-L236

This recording is with 5.3.1 from the firefox addons store:

![openwrt-working](https://user-images.githubusercontent.com/27789806/55652595-91e45900-57b1-11e9-96de-35a911957f98.gif)

**Comment by ghost** [comment] 2019-04-18 11:59
@mymindstorm 

It _does not work at the first login after the FF browser been restarted_. Once logged the manual way and logged out _and then logging in again it does work_, which seems curious.
