### ISSUE TITLE
Facebook 2Factor

### ISSUE THREAD

**Issue by LeonardoCiaccio** [Authenticator-Extension/Authenticator#241] opened 2018-11-10 10:01 UTC
Windows 10; Firefox 63.0.1 (64 bit); Your extension 5.2.1

On Facebook not recognize the QR

**Comment by mymindstorm** [comment] 2018-11-11 22:04
Duplicate of #174, use manual entry as a backup.

**Closed as completed by mymindstorm** 2018-11-11 22:04 UTC
Labels: duplicate
